Repository openstack-k8s-operators/telemetry-operator, pull requests merged in 2023-09, with the labels that each got.

#164 Support disconnected network environments
  .github/create_bundle.sh
  api/v1beta1/ceilometercentral_types.go
  api/v1beta1/ceilometercompute_types.go
  api/v1beta1/infracompute_types.go
  api/v1beta1/telemetry_types.go
  config/default/manager_default_images.yaml
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#171 use upstream kube-rbac-proxy instead of downstream
  config/default/manager_auth_proxy_patch.yaml
  config/samples/deploy.yaml
Labels: approved, lgtm

#170 Removing duplicated imports of telemetryv1beta1
  controllers/suite_test.go
  main.go
Labels: approved, lgtm

#174 Remove duplicate image env vars and constants
  .prow_ci.env
  api/v1beta1/ceilometercentral_types.go
  api/v1beta1/ceilometercompute_types.go
  api/v1beta1/telemetry_types.go
  config/default/manager_default_images.yaml
Labels: approved, lgtm

#172 Add autoscaling prometheus
  PROJECT
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/autoscaling_types.go
  api/v1beta1/conditions.go
  api/v1beta1/telemetry_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_autoscalings.yaml
  config/crd/patches/webhook_in_autoscalings.yaml
  config/rbac/autoscaling_editor_role.yaml
  config/rbac/autoscaling_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/telemetry_v1beta1_autoscaling.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
  controllers/autoscaling_controller.go
  controllers/telemetry_controller.go
  go.mod
  go.sum
  main.go
  pkg/autoscaling/const.go
  pkg/autoscaling/prometheus.go
Labels: approved, lgtm, needs-ok-to-test

#177 Avoid installing Prometheus by default
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/autoscaling_types.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
Labels: approved, lgtm

#178 Observability-operator dependency fix
  config/rbac/role.yaml
  controllers/autoscaling_controller.go
Labels: approved, lgtm

#169 Removing duplicated hashing logic
  controllers/ceilometercentral_controller.go
Labels: approved, lgtm

#179 Dataplane integration
  PROJECT
  README.md
  api/bases/telemetry.openstack.org_ceilometercentrals.yaml
  api/bases/telemetry.openstack.org_ceilometers.yaml
  api/bases/telemetry.openstack.org_infracomputes.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/ceilometer_types.go
  api/v1beta1/ceilometer_webhook.go
  api/v1beta1/ceilometercentral_webhook.go
  api/v1beta1/ceilometercompute_types.go
  api/v1beta1/ceilometercompute_webhook.go
  api/v1beta1/conditions.go
  api/v1beta1/infracompute_types.go
  api/v1beta1/infracompute_webhook.go
  api/v1beta1/telemetry_types.go
  api/v1beta1/telemetry_webhook.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.openstack.org_ceilometercentrals.yaml
  config/crd/bases/telemetry.openstack.org_ceilometers.yaml
  config/crd/bases/telemetry.openstack.org_infracomputes.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
  config/rbac/ceilometer_editor_role.yaml
  config/rbac/ceilometer_viewer_role.yaml
  config/rbac/ceilometercompute_editor_role.yaml
  config/rbac/ceilometercompute_viewer_role.yaml
  config/rbac/infracompute_editor_role.yaml
  config/rbac/infracompute_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/telemetry_v1beta1_ceilometer.yaml
  config/samples/telemetry_v1beta1_ceilometercompute.yaml
  config/samples/telemetry_v1beta1_infracompute.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
  config/webhook/manifests.yaml
  controllers/autoscaling_controller.go
  controllers/ceilometer_controller.go
  controllers/ceilometercompute_controller.go
  controllers/infracompute_controller.go
  controllers/telemetry_controller.go
  go.mod
  hack/clean_local_webhook.sh
  hack/configure_local_webhook.sh
  main.go
  pkg/ceilometer/const.go
  pkg/ceilometer/deployment.go
  pkg/ceilometer/initcontainer.go
  pkg/ceilometer/service.go
  pkg/ceilometer/volumes.go
  pkg/ceilometercentral/const.go
  pkg/ceilometercentral/initcontainer.go
  pkg/ceilometercentral/volumes.go
  pkg/ceilometercompute/ansibleee.go
  pkg/infracompute/ansibleee.go
  pkg/infracompute/const.go
  pkg/infracompute/volumes.go
Labels: approved

#180 Remove some ceilometercentral remains that prevented the image build
  README.md
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ceilometercentrals.yaml
  config/crd/patches/webhook_in_ceilometercentrals.yaml
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
  config/rbac/ceilometer_viewer_role.yaml
  config/samples/deploy.yaml
  config/samples/kustomization.yaml
Labels: approved

#181 Fix creation of CRD manifests via kustomize during build
  config/crd/kustomization.yaml
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#182 Fix the controller creation of two different sets of config-data
  controllers/ceilometer_controller.go
Labels: approved

#191 init.sh scripts not needed anymore
  templates/ceilometercentral/bin/.keep
  templates/ceilometercentral/bin/init.sh
  templates/ceilometercompute/bin/.keep
  templates/ceilometercompute/bin/init.sh
Labels: approved

#190 Disable storage polling by default
  templates/ceilometercentral/config/polling.yaml
Labels: approved

#193 Fix the sg-core version, using latest is no sane
  api/v1beta1/ceilometer_types.go
  config/default/manager_default_images.yaml
  config/samples/telemetry_v1beta1_ceilometer.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
Labels: approved, lgtm

#192 Added the github-check for edpm pipeline
  zuul.d/projects.yaml
Labels: approved, lgtm

#197 Replace CI approvers
  OWNERS_ALIASES
Labels: approved, lgtm
