Repository openstack-k8s-operators/telemetry-operator, pull requests merged in 2023-07, with the labels that each got.

#136 Added a service for CeilometerCentral and renamed everything in centr…
  config/rbac/role.yaml
  controllers/ceilometercentral_controller.go
  controllers/ceilometercompute_controller.go
  pkg/ceilometercentral/const.go
  pkg/ceilometercentral/service.go
Labels: approved

#139 Stop using playbooks and start using roles in ansibleee
  api/bases/telemetry.openstack.org_ceilometercomputes.yaml
  api/bases/telemetry.openstack.org_infracomputes.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/ceilometercompute_types.go
  api/v1beta1/infracompute_types.go
  config/crd/bases/telemetry.openstack.org_ceilometercomputes.yaml
  config/crd/bases/telemetry.openstack.org_infracomputes.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/samples/telemetry_v1beta1_ceilometercompute.yaml
  config/samples/telemetry_v1beta1_infracompute.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
  go.mod
  go.sum
  pkg/ceilometercompute/ansibleee.go
  pkg/infracompute/ansibleee.go
Labels: approved

#138 Update README
  README.md
Labels: approved, lgtm, ok-to-test

#141 Watch RBAC resources to trigger reconcile
  controllers/ceilometercentral_controller.go
  controllers/ceilometercompute_controller.go
  controllers/infracompute_controller.go
Labels: approved, lgtm

#140 Add CeilometerIpmi service
  api/bases/telemetry.openstack.org_ceilometercomputes.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/ceilometercompute_types.go
  api/v1beta1/ceilometercompute_webhook.go
  api/v1beta1/telemetry_types.go
  api/v1beta1/telemetry_webhook.go
  config/crd/bases/telemetry.openstack.org_ceilometercomputes.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/default/manager_default_images.yaml
  config/samples/telemetry_v1beta1_ceilometercompute.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
  controllers/ceilometercompute_controller.go
  templates/ceilometercompute/config/ceilometer-agent-ipmi.json
  templates/ceilometercompute/config/ceilometer_agent_ipmi.json
  templates/ceilometercompute/config/polling.yaml
Labels: approved, lgtm, ok-to-test

#143 Monitor TransportURL secret
  config/rbac/role.yaml
  controllers/ceilometercentral_controller.go
  controllers/ceilometercompute_controller.go
Labels: approved, lgtm

#144 Fix typo in repository url
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#147 Configure renovate to pin k8s and controller-runtime for dev preview and pin ocp
  go.mod
  go.sum
  renovate.json
Labels: approved, lgtm

#146 Changed pollster configuration to a production one for dev preview
  templates/ceilometercentral/config/polling.yaml
  templates/ceilometercompute/config/polling.yaml
Labels: approved

#154 Revert "Remove config/manager/kustomization.yaml from .gitignore"
  .gitignore
Labels: approved, lgtm

#156 Avoid bumping own api module by renovate
  renovate.json
Labels: approved, lgtm

#157 Replace RabbitMqTransportURLReady by common condition
  api/v1beta1/conditions.go
  controllers/ceilometercentral_controller.go
  controllers/ceilometercompute_controller.go
  controllers/telemetry_controller.go
Labels: approved, lgtm
