Repository openstack-k8s-operators/telemetry-operator, pull requests merged in 2024-10, with the labels that each got.

#478 Add "node-exporter" to Node Exporter's job name in scrape config
  controllers/metricstorage_controller.go
  tests/kuttl/suites/metricstorage/tests/01-assert.yaml
  tests/kuttl/suites/metricstorage/tests/04-assert.yaml
  tests/kuttl/suites/tls/tests/02-assert.yaml
Labels: approved, lgtm

#494 [OSPRH-10380] Move dashboards to use go API
  controllers/metricstorage_controller.go
  main.go
Labels: approved, lgtm

#501 Fix running reconcileDelete on new instance
  controllers/ceilometer_controller.go
Labels: approved, lgtm

#502 [OSPRH-10612] fix persistent field defaulting
  api/v1beta1/metricstorage_webhook.go
Labels: approved, lgtm

#498 Remove csibbit from telemetry-approvers
  OWNERS_ALIASES
Labels: approved

#505 Add ksmCaBundleSecretNameField and ksmTLSField to the index
  controllers/ceilometer_controller.go
Labels: approved, lgtm

#504 [OSPRH-10035] Expand "Can't own" messages
  controllers/metricstorage_controller.go
Labels: approved, lgtm

#497 [OSPRH-10102] Remove Ipaddr field from logging
  api/bases/telemetry.openstack.org_loggings.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/logging_types.go
  config/crd/bases/telemetry.openstack.org_loggings.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  controllers/logging_controller.go
  tests/kuttl/suites/default/tests/01-deploy.yaml
  tests/kuttl/suites/logging/tests/00-deploy.yaml
Labels: approved, lgtm, ok-to-test

#510 Fixes for KSM
  api/v1beta1/telemetry_webhook.go
  pkg/availability/statefulset.go
Labels: approved, lgtm

#499 Add power monitoring dashboard
  controllers/metricstorage_controller.go
  pkg/dashboards/openstack-kepler.go
  pkg/metricstorage/dashboard_objects.go
  tests/kuttl/suites/metricstorage/tests/01-assert.yaml
  tests/kuttl/suites/metricstorage/tests/02-errors.yaml
  tests/kuttl/suites/metricstorage/tests/04-assert.yaml
Labels: approved, lgtm

#512 Upgrade sg-core to the new upstream image
  api/v1beta1/ceilometer_types.go
  config/default/manager_default_images.yaml
Labels: approved, lgtm

#508 Report error if fetching IPs or hostname for edpm nodes failed
  controllers/metricstorage_controller.go
Labels: approved, lgtm

#514 Add status to CLI
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_ceilometers.yaml
  api/bases/telemetry.openstack.org_loggings.yaml
  api/bases/telemetry.openstack.org_metricstorages.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/autoscaling_types.go
  api/v1beta1/ceilometer_types.go
  api/v1beta1/logging_types.go
  api/v1beta1/metricstorage_types.go
  api/v1beta1/telemetry_types.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_ceilometers.yaml
  config/crd/bases/telemetry.openstack.org_loggings.yaml
  config/crd/bases/telemetry.openstack.org_metricstorages.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#516 Create new secret to store ipmi configuration files
  controllers/ceilometer_controller.go
  pkg/ceilometer/const.go
  templates/ceilometeripmi/bin/.keep
  templates/ceilometeripmi/config/ceilometer-agent-ipmi.json
  templates/ceilometeripmi/config/ceilometer.conf
  templates/ceilometeripmi/config/ceilometer_agent_ipmi.json
  templates/ceilometeripmi/config/polling.yaml
Labels: approved, lgtm

#517 [OSPRH-10800] Watch MetricStorage from Autoscaling
  controllers/autoscaling_controller.go
Labels: approved, lgtm

#521 Switch to use new CreateServiceReadyCondition
  api/go.mod
  api/go.sum
  controllers/aodh_controller.go
  controllers/ceilometer_controller.go
  go.mod
  go.sum
Labels: approved, lgtm

#522 Improve automated support for local webhooks
  Makefile
  hack/run_with_local_webhook.sh
Labels: approved, lgtm
