Repository openstack-k8s-operators/telemetry-operator, pull requests merged in 2024-07, with the labels that each got.

#422 Add Required Infrastructure Annotations to CSV
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#425 The control plane CR changed name
  ci/check-default-telemetry.yml
Labels: approved, lgtm

#430 Adding patch rbac perm for serviceaccounts
  config/rbac/role.yaml
  controllers/autoscaling_controller.go
  controllers/ceilometer_controller.go
  controllers/logging_controller.go
  controllers/metricstorage_controller.go
  controllers/telemetry_controller.go
Labels: lgtm

#428 [OSPRH-8065] Rework custom prometheus CA
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/autoscaling_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  controllers/autoscaling_controller.go
  pkg/autoscaling/aodh_statefulset.go
  pkg/autoscaling/const.go
  pkg/autoscaling/volumes.go
Labels: approved, lgtm

#429 [OSPRH-8074] Fix panic when missing ScrapeInterval
  pkg/metricstorage/service_monitor.go
Labels: approved, lgtm

#411 Update hooks in Zuul jobs
  ci/vars-default-telemetry.yml
  ci/vars-logging.yml
Labels: approved, lgtm

#424 [OSPRH-8076] Fix CustomMonitoringStack
  api/bases/telemetry.openstack.org_metricstorages.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/metricstorage_types.go
  api/v1beta1/metricstorage_webhook.go
  config/crd/bases/telemetry.openstack.org_metricstorages.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  controllers/metricstorage_controller.go
  controllers/telemetry_controller.go
  tests/kuttl/suites/metricstorage/tests/01-deploy.yaml
  tests/kuttl/suites/metricstorage/tests/02-disable-dashboards.yaml
  tests/kuttl/suites/metricstorage/tests/03-prepare-for-custom-monitoring-stack.yaml
  tests/kuttl/suites/metricstorage/tests/04-assert.yaml
  tests/kuttl/suites/metricstorage/tests/04-custom-monitoring-stack.yaml
Labels: approved, lgtm

#434 [OSPRH-8065] Change autoscaling TLS condition
  controllers/autoscaling_controller.go
Labels: approved, lgtm

#436 Bump lib common proposed
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm

#437 Remove Icon from bundle
  config/manifests/bases/telemetry-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#439 [OSPRH-8535] DataplaneNetwork should be optional
  api/bases/telemetry.openstack.org_metricstorages.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/metricstorage_types.go
  config/crd/bases/telemetry.openstack.org_metricstorages.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
Labels: approved, lgtm

#441 Update cpu threshold for autoscaling job
  ci/vars-autoscaling-tempest.yml
Labels: approved, lgtm, ok-to-test

#445 Adding the bundle build and usage procedure in the README
  README.md
Labels: approved, lgtm

#426 Removing RabbitMQ replace
  go.mod
Labels: approved, lgtm

#444 [OSPRH-8582] telemetry-operator must support empty template
  api/v1beta1/metricstorage_types.go
  api/v1beta1/metricstorage_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/metricstorage_controller.go
Labels: approved, lgtm

#432 Move to VerifySecret
  controllers/autoscaling_controller.go
  controllers/ceilometer_controller.go
  controllers/telemetry_common.go
Labels: approved, lgtm, ok-to-test

#451 network is a non-existent field, removing it from kuttl tests
  tests/kuttl/suites/default/tests/01-deploy.yaml
  tests/kuttl/suites/logging/tests/00-deploy.yaml
Labels: approved, lgtm

#435 [OSPRH-8075] Extend default-telemetry
  ci/check-default-telemetry.yml
Labels: approved, lgtm

#448 Revert "Remove memcached from autoscaling"
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/autoscaling_types.go
  api/v1beta1/autoscaling_webhook.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/rbac/role.yaml
  config/samples/telemetry_v1beta1_autoscaling.yaml
  config/samples/telemetry_v1beta1_autoscaling_tls.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
  config/samples/telemetry_v1beta1_telemetry_tls.yaml
  controllers/autoscaling_controller.go
  main.go
  templates/autoscaling/config/aodh.conf
  tests/kuttl/suites/autoscaling/tests/01-deploy.yaml
  tests/kuttl/suites/default/tests/01-deploy.yaml
  tests/kuttl/suites/tls/tests/02-deploy.yaml
Labels: approved, lgtm

#456 [18.0.0-proposed] Bump lib-common due to antiaffinity weight change
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm
