Repository openstack-k8s-operators/telemetry-operator, pull requests merged in 2024-04, with the labels that each got.

#355 Moved the constants to a telemetry-wide file for bettery readability
  api/v1beta1/telemetry_consts.go
Labels: approved

#359 Re-init conditions each reconcile
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/telemetry_types.go
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  controllers/autoscaling_controller.go
  controllers/ceilometer_controller.go
  controllers/logging_controller.go
  controllers/metricstorage_controller.go
  controllers/telemetry_controller.go
  go.mod
  go.sum
Labels: approved, lgtm

#357 [OSPRH-5732] ceilometer-central-agent must reboot when Keystone has a…
  controllers/ceilometer_controller.go
Labels: approved, lgtm

#363 [OSPRH-6229] Ceilometer gets 403 Forbidden when accessing Swift API
  controllers/ceilometer_controller.go
Labels: approved, lgtm

#358 Adding a Ceilometer-based VM dashboard
  controllers/metricstorage_controller.go
  pkg/dashboards/openstack-vm.go
  pkg/metricstorage/dashboard_prometheus_rule.go
Labels: approved, lgtm

#361 Rename ceilometer password selector
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_ceilometers.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/ceilometer_types.go
  api/v1beta1/telemetry_types.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_ceilometers.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  controllers/ceilometer_controller.go
  pkg/autoscaling/dbsync.go
Labels: approved, lgtm

#362 [tlse] Fix path to my.cnf file
  templates/autoscaling/config/aodh-api-config.json
  templates/autoscaling/config/aodh-dbsync-config.json
  templates/autoscaling/config/aodh-evaluator-config.json
  templates/autoscaling/config/aodh-listener-config.json
  templates/autoscaling/config/aodh-notifier-config.json
Labels: approved, lgtm

#365 [OSPRH-6312] Remove memcached from autoscaling
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/autoscaling_types.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
  config/rbac/role.yaml
  config/samples/telemetry_v1beta1_autoscaling.yaml
  config/samples/telemetry_v1beta1_autoscaling_tls.yaml
  config/samples/telemetry_v1beta1_telemetry.yaml
  config/samples/telemetry_v1beta1_telemetry_tls.yaml
  controllers/autoscaling_controller.go
  main.go
  templates/autoscaling/config/aodh.conf
  tests/kuttl/suites/autoscaling/tests/01-deploy.yaml
  tests/kuttl/suites/default/tests/01-deploy.yaml
  tests/kuttl/suites/tls/tests/02-deploy.yaml
Labels: approved, lgtm

#367 [OSPRH-6400] Rename ceilometer proxy image
  api/v1beta1/ceilometer_types.go
  api/v1beta1/ceilometer_webhook.go
Labels: approved, lgtm

#368 Use PodManagementPolicy: appsv1.ParallelPodManagement for the aodh statefulset
  pkg/autoscaling/aodh_statefulset.go
  pkg/ceilometer/statefulset.go
Labels: approved, lgtm

#323 [zuul] Update the external_plugin var
  ci/vars-autoscaling-tempest.yml
  zuul.d/projects.yaml
Labels: approved, lgtm, ok-to-test

#366 Manage ObservabilityUIPlugin for Dashboards plugin
  api/v1beta1/conditions.go
  config/rbac/role.yaml
  controllers/metricstorage_controller.go
  pkg/metricstorage/dashboard_datasource.go
Labels: approved, lgtm

#372 [OSPRH-6400] Add Proxy image to telemetry and default_images
  api/v1beta1/telemetry_types.go
  api/v1beta1/telemetry_webhook.go
  config/default/manager_default_images.yaml
Labels: approved, lgtm

#373 Update telemetry-approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#360 Improve defaulting
  api/bases/telemetry.openstack.org_autoscalings.yaml
  api/bases/telemetry.openstack.org_ceilometers.yaml
  api/bases/telemetry.openstack.org_telemetries.yaml
  api/v1beta1/autoscaling_types.go
  api/v1beta1/ceilometer_types.go
  api/v1beta1/metricstorage_webhook.go
  config/crd/bases/telemetry.openstack.org_autoscalings.yaml
  config/crd/bases/telemetry.openstack.org_ceilometers.yaml
  config/crd/bases/telemetry.openstack.org_telemetries.yaml
Labels: approved, lgtm

#379 [zuul] Bump COO install wait time
  ci/create-coo-subscription.yaml
Labels: approved, lgtm

#374 Ensure golangci-lint runs on all files
  .pre-commit-config.yaml
  controllers/autoscaling_controller.go
  controllers/ceilometer_controller.go
  controllers/logging_controller.go
  controllers/metricstorage_controller.go
  controllers/suite_test.go
  controllers/telemetry_controller.go
  main.go
  pkg/autoscaling/aodh_statefulset.go
  pkg/autoscaling/dbsync.go
  pkg/autoscaling/volumes.go
  pkg/ceilometer/statefulset.go
  pkg/ceilometer/volumes.go
  pkg/logging/service.go
  pkg/metricstorage/dashboard_prometheus_rule.go
Labels: approved, lgtm

#380 [zuul] Bump COO install timeout
  ci/create-coo-subscription.yaml
Labels: approved, lgtm

#375 Update probe timeouts
  pkg/autoscaling/aodh_statefulset.go
  pkg/ceilometer/statefulset.go
Labels: approved, lgtm, ok-to-test

#382 Remove unused selector on DashboardPrometheusRule
  controllers/metricstorage_controller.go
  pkg/metricstorage/dashboard_prometheus_rule.go
Labels: approved, lgtm

#364 [OSPRH-6229] Ceilometer gets 403 Forbidden when accessing Swift API
  controllers/ceilometer_controller.go
  go.mod
Labels: approved, lgtm
