Repository openstack-k8s-operators/telemetry-operator, pull requests merged in 2025-04, with the labels that each got.

#664 [OSPRH-14905][d-t] fix tasks reporting as skipped
  ci/default-telemetry/tasks/no_coo_autoscaling_metricstorage.yml
  ci/default-telemetry/tasks/test_custom_monitoring_stack.yml
Labels: approved, lgtm

#658 [CI] Deploy mysqldExporter with vars-autoscaling.yml
  ci/vars-autoscaling.yml
Labels: approved, lgtm

#667 [zuul] Convert graphing job to non-voting
  zuul.d/projects.yaml
Labels: approved, lgtm

#660 [run-with-webhook] Handle operator deploy by Openstack initialization
  hack/run_with_local_webhook.sh
Labels: approved, lgtm

#665 Dashboard Ceilometer IPMI - Solve Voltage name issue
  pkg/dashboards/openstack-ceilometer-ipmi.go
Labels: approved, lgtm

#669 Add make force-bump target
  Makefile
Labels: approved, lgtm

#670 OSPRH-13452: Use functional-autoscaling-tests-osp18 job instead of the alias functional-tests-on-osp18
  zuul.d/projects.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#672 Fix go.mod checksum mismatch
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#673 OSPRH-15988: Enable dashboards for Run Graphing Console UI tests
  ci/vars-autoscaling.yml
Labels: approved, lgtm, needs-ok-to-test, jira/valid-reference

#676 [zuul] Stop running the metrics-verification test
  zuul.d/projects.yaml
Labels: approved, lgtm

#675 Add force-bump-pull-request workflows
  .github/workflows/force-bump-pr-manual.yaml
  .github/workflows/force-bump-pr-scheduled.yaml
Labels: approved, lgtm

#645 Reconfigure ceilometer-compute agents to enable prom-exporter
  api/v1beta1/telemetry_consts.go
  controllers/metricstorage_controller.go
  templates/ceilometercompute/config/ceilometer.conf
  tests/kuttl/suites/metricstorage/tests/01-assert.yaml
  tests/kuttl/suites/metricstorage/tests/04-assert.yaml
Labels: approved, lgtm
